repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.3
  hooks:
    # Run the linter.
    - id: ruff
      entry: ruff check
      args: [ --fix ]

    - id: ruff-format
      entry: ruff format

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.11.0
    hooks:
      - id: commitlint
        additional_dependencies: ['@commitlint/config-conventional']
        stages: [commit-msg]
