on:
    push:
        branches: [ master, main ]

  permissions:
    id-token: write
    contents: read

  jobs:
    TestDeploy:
      runs-on: ubuntu-latest
      steps:
        - name: Git clone the repository
          uses: actions/checkout@v4
  
        - uses: actions/setup-python@v5
          id: setup_python
          with: 
            python-version: '3.13'
  
        - name: restore cached venv
          uses: actions/cache/restore@v4
          with:
            key: venv-${{ hashFiles('requirements.txt') }}
            path: .venv
  
        - name: install deps
          run: |
            python -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
        
        - name: cache venv
          uses: actions/cache/save@v4
          with: 
            key: venv-${{ hashFiles('requirements.txt') }}
            path: .venv
  
        # - name: create base lambda layer
        #   run: |
        #     zip -r layer_content.zip .venv/lib
  
        # - name: configure aws credentials
        #   uses: aws-actions/configure-aws-credentials@v4.0.3
        #   with:
        #     role-to-assume: <role>
        #     aws-region: eu-west-1
  
        # - name: upload lambda base layer
        #   run: |
        #     aws lambda publish-layer-version \
        #       --layer-name IntercomNotifications-base-layer \
        #       --zip-file fileb://layer_content.zip
  