on:
  push:
    branches: [ master, main ]

permissions:
  id-token: write
  contents: read

jobs:
  TestDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.3
        with:
          role-to-assume: GitHubActionsOIDCKieranManningDeployRole
          aws-region: eu-west-1